version: '3'

services:
  tomcat_1_node_1:
    ports:
      - "8080:8080"    
    image: tomcat:9-jdk8
    environment:
      JAVA_OPTS: "-Xms2g -Xmx4g -XX:MaxPermSize=256m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:HeapDumpPath=/working-dir/heap-dump/ -server"      
      INSTANCE_NAME: tomcat_1_node_1
      WORKING_DIR: "/working-dir/"
      DBUSER: user
      DBPASS: pass     
      DBHOST: 127.0.0.1
      DBPORT: 5432
      DBNAME: database_name
    container_name: amplisync-qa
    restart: unless-stopped
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./working-dir:/working-dir
